command line args [--model_name LightGCN --dataset_name ml-100k --n_layers 1, --learning_rate 0.001, --embed_size 32,] will not be used in RecBole
Traceback (most recent call last):
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 80, in <module>
    Fire(main)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 23, in main
    if args[i].isdigit():
AttributeError: 'tuple' object has no attribute 'isdigit'
command line args [--model_name LightGCN --dataset_name ml-100k --n_layers 1, --learning_rate 0.001, --embed_size 64,] will not be used in RecBole
Traceback (most recent call last):
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 80, in <module>
    Fire(main)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 23, in main
    if args[i].isdigit():
AttributeError: 'tuple' object has no attribute 'isdigit'
command line args [--model_name LightGCN --dataset_name ml-100k --n_layers 1, --learning_rate 0.001, --embed_size 128] will not be used in RecBole
Traceback (most recent call last):
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 80, in <module>
    Fire(main)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 23, in main
    if args[i].isdigit():
AttributeError: 'tuple' object has no attribute 'isdigit'
command line args [--model_name LightGCN --dataset_name ml-100k --n_layers 1, --learning_rate 0.0001, --embed_size 32,] will not be used in RecBole
Traceback (most recent call last):
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 80, in <module>
    Fire(main)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 23, in main
    if args[i].isdigit():
AttributeError: 'tuple' object has no attribute 'isdigit'
command line args [--model_name LightGCN --dataset_name ml-100k --n_layers 1, --learning_rate 0.0001, --embed_size 64,] will not be used in RecBole
Traceback (most recent call last):
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 80, in <module>
    Fire(main)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 23, in main
    if args[i].isdigit():
AttributeError: 'tuple' object has no attribute 'isdigit'
command line args [--model_name LightGCN --dataset_name ml-100k --n_layers 1, --learning_rate 0.0001, --embed_size 128] will not be used in RecBole
Traceback (most recent call last):
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 80, in <module>
    Fire(main)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 23, in main
    if args[i].isdigit():
AttributeError: 'tuple' object has no attribute 'isdigit'
command line args [--model_name LightGCN --dataset_name ml-100k --n_layers 1, --learning_rate 0.00001 --embed_size 32,] will not be used in RecBole
Traceback (most recent call last):
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 80, in <module>
    Fire(main)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 23, in main
    if args[i].isdigit():
AttributeError: 'tuple' object has no attribute 'isdigit'
command line args [--model_name LightGCN --dataset_name ml-100k --n_layers 1, --learning_rate 0.00001 --embed_size 64,] will not be used in RecBole
Traceback (most recent call last):
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 80, in <module>
    Fire(main)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 23, in main
    if args[i].isdigit():
AttributeError: 'tuple' object has no attribute 'isdigit'
command line args [--model_name LightGCN --dataset_name ml-100k --n_layers 1, --learning_rate 0.00001 --embed_size 128] will not be used in RecBole
Traceback (most recent call last):
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 80, in <module>
    Fire(main)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 23, in main
    if args[i].isdigit():
AttributeError: 'tuple' object has no attribute 'isdigit'
command line args [--model_name LightGCN --dataset_name ml-100k --n_layers 2, --learning_rate 0.001, --embed_size 32,] will not be used in RecBole
Traceback (most recent call last):
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 80, in <module>
    Fire(main)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 23, in main
    if args[i].isdigit():
AttributeError: 'tuple' object has no attribute 'isdigit'
command line args [--model_name LightGCN --dataset_name ml-100k --n_layers 2, --learning_rate 0.001, --embed_size 64,] will not be used in RecBole
Traceback (most recent call last):
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 80, in <module>
    Fire(main)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 23, in main
    if args[i].isdigit():
AttributeError: 'tuple' object has no attribute 'isdigit'
command line args [--model_name LightGCN --dataset_name ml-100k --n_layers 2, --learning_rate 0.001, --embed_size 128] will not be used in RecBole
Traceback (most recent call last):
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 80, in <module>
    Fire(main)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 23, in main
    if args[i].isdigit():
AttributeError: 'tuple' object has no attribute 'isdigit'
command line args [--model_name LightGCN --dataset_name ml-100k --n_layers 2, --learning_rate 0.0001, --embed_size 32,] will not be used in RecBole
Traceback (most recent call last):
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 80, in <module>
    Fire(main)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 23, in main
    if args[i].isdigit():
AttributeError: 'tuple' object has no attribute 'isdigit'
command line args [--model_name LightGCN --dataset_name ml-100k --n_layers 2, --learning_rate 0.0001, --embed_size 64,] will not be used in RecBole
Traceback (most recent call last):
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 80, in <module>
    Fire(main)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 23, in main
    if args[i].isdigit():
AttributeError: 'tuple' object has no attribute 'isdigit'
command line args [--model_name LightGCN --dataset_name ml-100k --n_layers 2, --learning_rate 0.0001, --embed_size 128] will not be used in RecBole
Traceback (most recent call last):
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 80, in <module>
    Fire(main)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 23, in main
    if args[i].isdigit():
AttributeError: 'tuple' object has no attribute 'isdigit'
command line args [--model_name LightGCN --dataset_name ml-100k --n_layers 2, --learning_rate 0.00001 --embed_size 32,] will not be used in RecBole
Traceback (most recent call last):
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 80, in <module>
    Fire(main)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 23, in main
    if args[i].isdigit():
AttributeError: 'tuple' object has no attribute 'isdigit'
command line args [--model_name LightGCN --dataset_name ml-100k --n_layers 2, --learning_rate 0.00001 --embed_size 64,] will not be used in RecBole
Traceback (most recent call last):
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 80, in <module>
    Fire(main)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 23, in main
    if args[i].isdigit():
AttributeError: 'tuple' object has no attribute 'isdigit'
command line args [--model_name LightGCN --dataset_name ml-100k --n_layers 2, --learning_rate 0.00001 --embed_size 128] will not be used in RecBole
Traceback (most recent call last):
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 80, in <module>
    Fire(main)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 23, in main
    if args[i].isdigit():
AttributeError: 'tuple' object has no attribute 'isdigit'
command line args [--model_name LightGCN --dataset_name ml-100k --n_layers 3 --learning_rate 0.001, --embed_size 32,] will not be used in RecBole
Traceback (most recent call last):
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 80, in <module>
    Fire(main)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 23, in main
    if args[i].isdigit():
AttributeError: 'int' object has no attribute 'isdigit'
command line args [--model_name LightGCN --dataset_name ml-100k --n_layers 3 --learning_rate 0.001, --embed_size 64,] will not be used in RecBole
Traceback (most recent call last):
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 80, in <module>
    Fire(main)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 23, in main
    if args[i].isdigit():
AttributeError: 'int' object has no attribute 'isdigit'
command line args [--model_name LightGCN --dataset_name ml-100k --n_layers 3 --learning_rate 0.001, --embed_size 128] will not be used in RecBole
Traceback (most recent call last):
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 80, in <module>
    Fire(main)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 23, in main
    if args[i].isdigit():
AttributeError: 'int' object has no attribute 'isdigit'
command line args [--model_name LightGCN --dataset_name ml-100k --n_layers 3 --learning_rate 0.0001, --embed_size 32,] will not be used in RecBole
Traceback (most recent call last):
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 80, in <module>
    Fire(main)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 23, in main
    if args[i].isdigit():
AttributeError: 'int' object has no attribute 'isdigit'
command line args [--model_name LightGCN --dataset_name ml-100k --n_layers 3 --learning_rate 0.0001, --embed_size 64,] will not be used in RecBole
Traceback (most recent call last):
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 80, in <module>
    Fire(main)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 23, in main
    if args[i].isdigit():
AttributeError: 'int' object has no attribute 'isdigit'
command line args [--model_name LightGCN --dataset_name ml-100k --n_layers 3 --learning_rate 0.0001, --embed_size 128] will not be used in RecBole
Traceback (most recent call last):
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 80, in <module>
    Fire(main)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 23, in main
    if args[i].isdigit():
AttributeError: 'int' object has no attribute 'isdigit'
command line args [--model_name LightGCN --dataset_name ml-100k --n_layers 3 --learning_rate 0.00001 --embed_size 32,] will not be used in RecBole
Traceback (most recent call last):
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 80, in <module>
    Fire(main)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 23, in main
    if args[i].isdigit():
AttributeError: 'int' object has no attribute 'isdigit'
command line args [--model_name LightGCN --dataset_name ml-100k --n_layers 3 --learning_rate 0.00001 --embed_size 64,] will not be used in RecBole
Traceback (most recent call last):
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 80, in <module>
    Fire(main)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 23, in main
    if args[i].isdigit():
AttributeError: 'int' object has no attribute 'isdigit'
command line args [--model_name LightGCN --dataset_name ml-100k --n_layers 3 --learning_rate 0.00001 --embed_size 128] will not be used in RecBole
Traceback (most recent call last):
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 80, in <module>
    Fire(main)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/minseo/anaconda3/envs/recbole/lib/python3.8/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/minseo/now_exper/rb/Recbole/train.py", line 23, in main
    if args[i].isdigit():
AttributeError: 'int' object has no attribute 'isdigit'
